set columns=169
set lines=49
winpos 286 0
set guifont=Consolas:h11
set winaltkeys=yes

set guioptions-=T "get rid of toolbar
"set guioptions-=m "get rid of menu 
"set guifont=-adobe-courier-medium-r-*-*-14-*-*-*-*-*-*-*
syntax on
colorscheme darkblue
hi Visual gui=none guifg=black guibg=gray

" kill visual bell
set t_vb=

