set columns=169
set lines=49
winpos 286 0
set winaltkeys=yes

"set background=dark
"colorscheme darkblue
"colorscheme visualstudio
"colorscheme espresso

set guioptions-=T "get rid of toolbar
set guioptions-=t "get rid of tearoff menus
"set guioptions-=m "get rid of menu 
"set guifont=-adobe-courier-medium-r-*-*-14-*-*-*-*-*-*-*
"syntax on


" Override any fonts set in the colorscheme
set guifont=Consolas:h11:cANSI:qDRAFT

"hi Visual gui=none guifg=black guibg=gray

" kill visual bell
set t_vb=

