set columns=169
set lines=49
winpos 286 0
set winaltkeys=yes

"colorscheme darkblue
colorscheme visualstudio

set guioptions-=T "get rid of toolbar
"set guioptions-=m "get rid of menu 
"set guifont=-adobe-courier-medium-r-*-*-14-*-*-*-*-*-*-*
syntax on


" Override any fonts set in the colorscheme
set guifont=Consolas:h11:cANSI:qDRAFT

"hi Visual gui=none guifg=black guibg=gray

" kill visual bell
set t_vb=

